theme: jekyll-theme-cayman

# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://www.ttzero.org
date_format: "ordinal"
title: 『奈留·智库』
subtitle: "Home page"
description: "智库的个人博客"
keywords: eec,excel,智库,奈留·智库
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 4

# ---------------- #
#      Author      #
# ---------------- #
author: guanquan.wang
organization:
organization_url:
github_username: wangguanquan
location: Suzhou, China
email: guanquan.wang@yandex.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#      Jekyll      #
# ---------------- #
paginate: 10

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10